version: "2"

includes:
  alacritty: ./alacritty.d
  fish: ./fish.d
  git: ./git.d
  karabiner: ./karabiner.d

tasks:
  clean:
    deps:
      - alacritty:clean
      - fish:clean
      - git:clean
      - karabiner:clean

  install:
    deps:
      - alacritty:install
      - fish:install
      - git:install
      - karabiner:install
