version: "2"

includes:
  fish: ./fish.d
  git: ./git.d
  starship: ./starship.d

tasks:
  clean:
    deps:
      - fish:clean
      - git:clean
      - starship:clean

  install:
    deps:
      - fish:install
      - git:install
      - starship:install
